package web

import "strings"

// connectedWorkloadPatternAllowed is deliberately an exact list of local mux
// patterns. Adding an owner-only route cannot silently expose it to attached
// instances. Both ends check this list; aliases, unknown methods and nested
// proxy/registry routes have no matching entry.
func connectedWorkloadPatternAllowed(pattern string) bool {
	switch pattern {
	case "DELETE /api/board/links",
		"DELETE /api/configuration/{kind}/{name}",
		"DELETE /api/mcp/servers/{name}",
		"DELETE /api/projects/{id}",
		"DELETE /api/projects/{id}/charts/{chart_id}",
		"DELETE /api/providers/{provider}/account/device",
		"DELETE /api/providers/{provider}/account/link",
		"DELETE /api/routines/{id}",
		"DELETE /api/sessions/{id}",
		"DELETE /api/sessions/{id}/file-grants/{grant_id}",
		"DELETE /api/sessions/{id}/queue/{request_id}",
		"GET /api/board",
		"GET /api/board/cards/{ref}",
		"GET /api/board/executor",
		"GET /api/board/projects/{id}",
		"GET /api/configuration",
		"GET /api/events",
		"GET /api/events/detail",
		"GET /api/fs/dirs",
		"GET /api/mcp",
		"GET /api/meta",
		"GET /api/previous/counts",
		"GET /api/projects",
		"GET /api/projects/{id}/charts",
		"GET /api/projects/{id}/files",
		"GET /api/projects/{id}/previous",
		"GET /api/projects/{id}/routines",
		"GET /api/projects/{id}/terminal",
		"GET /api/providers/{provider}/account",
		"GET /api/providers/{provider}/account/device",
		"GET /api/providers/{provider}/cli",
		"GET /api/routines",
		"GET /api/sessions",
		"GET /api/sessions/{id}",
		"GET /api/sessions/{id}/attachments/{attachment_id}",
		"GET /api/sessions/{id}/changes",
		"GET /api/sessions/{id}/changes/file",
		"GET /api/sessions/{id}/chart",
		"GET /api/sessions/{id}/commands",
		"GET /api/sessions/{id}/evidence",
		"GET /api/sessions/{id}/export",
		"GET /api/sessions/{id}/files",
		"GET /api/sessions/{id}/files/raw",
		"GET /api/sessions/{id}/files/tree",
		"GET /api/sessions/{id}/files/view/{path...}",
		"GET /api/sessions/{id}/git",
		"GET /api/sessions/{id}/history",
		"GET /api/sessions/{id}/items/{item_id}",
		"GET /api/sessions/{id}/mcp",
		"GET /api/sessions/{id}/subagents",
		"GET /api/sessions/{id}/subagents/{agent_id}",
		"GET /api/sessions/{id}/subagents/{agent_id}/history",
		"GET /api/settings",
		"GET /api/usage",
		"GET /api/usage/prices",
		"GET /api/usage/tokens",
		"GET /api/utility",
		"PATCH /api/board/cards/{ref}",
		"PATCH /api/board/projects/{id}",
		"PATCH /api/mcp/servers/{name}",
		"PATCH /api/projects/{id}",
		"PATCH /api/routines/{id}",
		"PATCH /api/sessions/{id}",
		"PATCH /api/settings",
		"POST /api/board/cards",
		"POST /api/board/cards/{ref}/attach",
		"POST /api/board/cards/{ref}/check",
		"POST /api/board/cards/{ref}/comments",
		"POST /api/board/cards/{ref}/confirm",
		"POST /api/board/cards/{ref}/dismiss",
		"POST /api/board/cards/{ref}/launch",
		"POST /api/board/cards/{ref}/move",
		"POST /api/board/cards/{ref}/plan",
		"POST /api/board/cards/{ref}/release",
		"POST /api/board/cards/{ref}/restore",
		"POST /api/board/cards/{ref}/split",
		"POST /api/board/cards/{ref}/status",
		"POST /api/board/cards/{ref}/suggest",
		"POST /api/board/cards/{ref}/triage",
		"POST /api/board/import",
		"POST /api/board/links",
		"POST /api/board/purge",
		"POST /api/board/requests/{id}/accept",
		"POST /api/board/requests/{id}/reject",
		"POST /api/configuration/skills/install",
		"POST /api/configuration/skills/list",
		"POST /api/configuration/{kind}/draft",
		"POST /api/fs/dirs",
		"POST /api/mcp/servers",
		"POST /api/projects",
		"POST /api/projects/{id}/charts/{chart_id}/refresh",
		"POST /api/projects/{id}/previous/{conversation_id}/import",
		"POST /api/projects/{id}/routines",
		"POST /api/providers/{provider}/account/device",
		"POST /api/providers/{provider}/account/sign-in",
		"POST /api/providers/{provider}/account/sign-out",
		"POST /api/providers/{provider}/cli/update",
		"POST /api/routines/{id}/run",
		"POST /api/sessions",
		"POST /api/sessions/{id}/archive",
		"POST /api/sessions/{id}/attachments",
		"POST /api/sessions/{id}/background-tasks/{task_id}/cancel",
		"POST /api/sessions/{id}/cancel",
		"POST /api/sessions/{id}/chart/pin",
		"POST /api/sessions/{id}/close",
		"POST /api/sessions/{id}/command",
		"POST /api/sessions/{id}/file-grants",
		"POST /api/sessions/{id}/files/resolve",
		"POST /api/sessions/{id}/git/commit",
		"POST /api/sessions/{id}/git/init",
		"POST /api/sessions/{id}/git/message",
		"POST /api/sessions/{id}/git/pull",
		"POST /api/sessions/{id}/git/push",
		"POST /api/sessions/{id}/interactions/{iid}",
		"POST /api/sessions/{id}/mcp/reconnect",
		"POST /api/sessions/{id}/mcp/servers/{name}/disable",
		"POST /api/sessions/{id}/mcp/servers/{name}/enable",
		"POST /api/sessions/{id}/mcp/servers/{name}/restart",
		"POST /api/sessions/{id}/mcp/servers/{name}/sign-in",
		"POST /api/sessions/{id}/mcp/servers/{name}/sign-in/finish",
		"POST /api/sessions/{id}/prompt",
		"POST /api/sessions/{id}/queue/clear",
		"POST /api/sessions/{id}/queue/resume",
		"POST /api/sessions/{id}/reopen",
		"POST /api/sessions/{id}/rerun",
		"POST /api/sessions/{id}/settle",
		"POST /api/sessions/{id}/subagents/{agent_id}/cancel",
		"POST /api/sessions/{id}/subagents/{agent_id}/prompt",
		"POST /api/sessions/{id}/suggestions",
		"POST /api/settings/custom-models/discover",
		"PUT /api/configuration/{kind}/{name}",
		"PUT /api/mcp/servers/{name}",
		grantKeyRoute:
		return true
	default:
		return false
	}
}

// connectedAccountGated lists the workload routes refused to a connection
// whose Copilot account breaks the one-account rule: work that runs an agent
// (creating, prompting or resuming Tasks, routine runs, drafts), the
// planner's writes and the terminal. Reads, Settings and the account routes
// stay open, so the account can be fixed there.
func connectedAccountGated(pattern string) bool {
	if method, route, _ := strings.Cut(pattern, " "); method != "GET" && strings.HasPrefix(route, "/api/board") {
		return true
	}
	switch pattern {
	case "GET /api/projects/{id}/terminal",
		"POST /api/configuration/{kind}/draft",
		"POST /api/projects/{id}/previous/{conversation_id}/import",
		"POST /api/routines/{id}/run",
		"POST /api/sessions",
		"POST /api/sessions/{id}/command",
		"POST /api/sessions/{id}/git/message",
		"POST /api/sessions/{id}/interactions/{iid}",
		"POST /api/sessions/{id}/prompt",
		"POST /api/sessions/{id}/queue/resume",
		"POST /api/sessions/{id}/rerun",
		"POST /api/sessions/{id}/subagents/{agent_id}/prompt",
		"POST /api/sessions/{id}/suggestions":
		return true
	default:
		return false
	}
}
